### ISSUE TITLE
Virus threats detected in `prototypes` directory

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/hydrogen-web#1076]
**Describe the bug**
Virus threats are detected in the `prototypes` directory. Probably false positives but it'd be good to get rid of them if possible.

**To Reproduce**
Scan the `prototypes` directory with ClamAV.

**Expected behavior**
No threats detected

**Actual behavior**
3 threats detected of type `PUA.Html.Trojan.Agent-37075`

**Screenshots**
![image](https://user-images.githubusercontent.com/4940864/232031744-855477a6-e18e-47a6-a16a-159958a37987.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version 0.3.8

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by davidegirardi** [comment]
When did you update your definitions? I don't get any (false) positive with clamav here.

**Comment by jonnyandrew** [comment]
I discovered this is only an issue when ClamAV is configured to additionally check for PUAs (potentially unwanted applications) and according to the [FAQ](https://docs.clamav.net/faq/faq-pua.html#current-pua-categories) I should expect to see more false positives when that option is enabled.

**Comment by MidhunSureshR** [comment]
Closing this issue since we all agree that this is a false positive.
