### ISSUE TITLE
olm-3.2.14.tgz  Doesn't seem to exist

### ISSUE THREAD

**Issue by 337077418** [vector-im/hydrogen-web#1146]
error An unexpected error occurred: "https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.14.tgz: read ECONNRESET".

**Comment by MidhunSureshR** [comment]
A bit more information would be nice. Where exactly do you see this error?

**Comment by 337077418** [comment]
> 如果能提供更多信息就更好了。您到底在哪里看到这个错误？

PS H:\hydrogen-web-master> yarn install
Debugger attached.
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.14.tgz: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information provided in "H:\\hydrogen-web-master\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Waiting for the debugger to disconnect...

**Comment by 337077418** [comment]
![image](https://github.com/vector-im/hydrogen-web/assets/10607980/fdea3305-0f44-4fa4-92ff-d1af1431e1c9)

**Comment by MidhunSureshR** [comment]
https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.14.tgz downloads fine for me so it looks like some sort of issue on your end? maybe it's geo-blocked?

**Comment by 337077418** [comment]
> https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.14.tgz下载对我来说很好，所以看起来比如你这边有什么问题吗？也许它被地理封锁了？

Are there any packages for non matrix.org domain names? The matrix.org domain name seems to be inaccessible in some countries and cannot be downloaded even when using VPN

**Comment by uhoreg** [comment]
olm is now in npm: https://www.npmjs.com/package/@matrix-org/olm  So if you update the `package.json` to use `"@matrix-org/olm": "3.2.15"`, then it should work.

**Comment by 337077418** [comment]
> https://www.npmjs.com/package/@matrix-org/olm

Thank you very much. It has been resolved
