### ISSUE TITLE
Reply links don't open a new tab/window

### ISSUE THREAD

**Issue by b100dian** [vector-im/hydrogen-web#1157]
**Describe the bug**
When somebody uses the reply quote, a link "In reply to" appears in the conversation. Clicking that link goes to the matrix.to URL in the current window/tab instead of opening a new one.

**To Reproduce**
1. Click on '...' in a message and select "Reply"
2. Add a reply message and post/send it
3. Click the "In reply to" link inside your message.

**Expected behavior**
The hydrogen client is not left to go to the matrix.to url

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Sailfish OS
 - Browser sailfishos-browser
 - Version 78

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 8
 - OS: Sailfish OS
 - Browser SailfishOS browser
 - Version 78

**Additional context**
An easy fix may be https://github.com/hydrogen-sailfishos/hydrogen-web/commit/f0cfa66cd89b068deceae39d21ceb5d531f89708

**Comment by q-TheDog** [comment]
Shouldn't it scroll to the message that was replied to in the existing tab instead of opening in a new tab? Opening a new tab would cause duplicate hydrogen clients to be opened which can cause syncing issues and takes up more RAM.

**Comment by b100dian** [comment]
Yes, that would be the better behaviour indeed. Right now it just navigates to another site [1](`matrix.to`) then that other site might trigger loading of element or another client [2].
The 1st step is problematic for Sailfish hydrogen packaging because the whole webview app is replaced with `matrix.to` then the next click might open another client and the current one becomes unusable, and might be a problem for other users too, that's why this would be the shortest solution, to open in a new tab - this also means that the app can detect the new link being clicked and offer to open it in the browser.
To rehash, I would agree that you're describing the best solution, this is just (and the associated PR) a simple workaround.
