### ISSUE TITLE
Cannot view nor download any received image when using the torbrowser

### ISSUE THREAD

**Issue by guidomz** [vector-im/hydrogen-web#1186]
**Describe the bug**
When using the torbrowser, I cannot view nor download images sent to me. Timeline merely shows a blank placeholder that when clicked shows a similarly blank overlay. When I try to download, the file is not an image, despite it being named as jpg or png, but is instead a json file containing this:
```json
{"errcode":"M_MISSING_TOKEN","error":"no token provided (required)","mr_errcode":"M_MISSING_TOKEN"}
```

I can send images but the timeline shows the same thing as when I receive images. On the positive side, the recipient can view and download images I send.

**To Reproduce**
Tried to access the timeline using a different browser (non-torbrowser) and the image is shown on the timeline and is downloadable.

**Expected behavior**
Image is visible on the timeline (preview) and is downloadable even when using the torbrowser.

**Desktop (please complete the following information):**
 - OS: Debian BookWorm
 - Browser: torbrowser
 - Version: 13.5.7 (64-bit)

**Additional context**
- This happens even after I provide and set up my Security key in the Settings page.
- I can send images when using the torbrowser. The recipient can successfully view and download images I send.

**Comment by MidhunSureshR** [comment]
torbrowser has service workers disabled by default.
See https://gitlab.torproject.org/tpo/applications/tor-browser/-/commit/726047a459acf9d8c26fcfdd72584f0196dd60ce
But you can turn it back on by going to `about:config` and setting `dom.serviceWorkers.enabled` to true.
