### ISSUE TITLE
Something went wrong: creating room encryption before encryption got globally enabled.

### ISSUE THREAD

**Issue by eMPee584** [vector-im/hydrogen-web#507]
**Describe the bug**
I had a session logged in in firefox on my laptop, it won't open up again, first trying
![image](https://user-images.githubusercontent.com/1227833/134314408-7639a31d-2715-4e84-8106-e563daa325c0.png)
then failing with the message:
![image](https://user-images.githubusercontent.com/1227833/134314173-1677c353-5040-475f-992f-4fc565442ded.png)
Should I just re-login (in which case this should be proposed below the error message) or is this something to be debugged and fixed?

**Desktop:**
 - OS: debian 10.10
 - Browser: firefox-esr 78.12.0esr-1~deb10u1

**Comment by bwindels** [comment]
this looks like #139. were you low on storage perhaps?

**Comment by eMPee584** [comment]
Actually I wouldn't think so.. but I'm using [profile-sync-daemon](https://github.com/graysky2/profile-sync-daemon) and there _might_ have been a subsequent unclean shutdown..
There seems to exist an IndexedDB session DB but all its stores are empty... the test and log DB do contain entries.

**Comment by bwindels** [comment]
Ah interesting (you didn't hit "clear" by any chance in the session picker screen?). Anyway, the fix for this will be the same as for #139 so will close as duplicate. Thanks for reporting!
