### ISSUE TITLE
Make Hydrogen Thread aware

### ISSUE THREAD

**Issue by germain-gg** [vector-im/hydrogen-web#552]
Threads are now using a `m.thread` relation.

Before this is fully ready to ship without a labs flag, there are a couple of client considerations that we can take to ensure maximum backwards compatibility and continuity in conversations when threads will be available to the masses.

[MSC3440](https://github.com/matrix-org/matrix-doc/pull/3440) recommends two things for clients that do not fully support threads yet

- [ ] To treat `m.thread` the same way that they treat `m.in_reply_to`
- [ ] To change the event references from `m.in_reply_to` to `m.thread` when replying to an event that has an `m.thread` relation (to ensure that the message will be displayed correctly in the thread when viewed on thread's ready clients)

**Comment by DanilaFe** [comment]
If the core team doesn't have time for this, I may be able to take a look - this seems manageable.

**Comment by bwindels** [comment]
Great @DanilaFe if you want to take a look at this. Let me know if you need any input!
