### ISSUE TITLE
Add ability to customize the top panel (in the upper right corner) and contact lines

### ISSUE THREAD

**Issue by altro3** [vector-im/hydrogen-web#555]
**Is your feature request related to a problem? Please describe.**

We use your widget in our project. At the moment we are faced with a problem: there is a need for a button for direct calls near each of the contacts, as well as in the upper chat panel. But we should have not just a call, but also custom logic.

At the moment, it is impossible to add call buttons to the display of contacts and to the top panel in any way - only to customize your project.

**Describe the solution you'd like**

I could contribute to your project and add this functionality, I think it will be useful to many. I think we need to make it flexible, i.e. it should be possible not only to customize the buttons on these panels, but also to hide them if they are not required.

**Additional context**

Examples:

Header panel: 
![изображение](https://user-images.githubusercontent.com/48474279/138593452-1e235584-ad19-4f8e-bd8a-ca11c1148e02.png)

Contact line: 
![изображение](https://user-images.githubusercontent.com/48474279/138593497-e0fc7935-a5a3-417d-8851-068b15fd3f28.png)

**Comment by bwindels** [comment]
As discussed, this is possible by using import overrides: https://github.com/vector-im/hydrogen-web/blob/master/doc/SKINNING.md#replacing-javascript-files
