### ISSUE TITLE
Hide old upgraded rooms

### ISSUE THREAD

**Issue by babolivier** [vector-im/hydrogen-web#567]
When a room upgrade is performed, Hydrogen still shows the old room in the room list instead of hiding it.

(as funny as it is to see "Dumbeldor, Evil Matthew, Github, Ken..." in my room list when a bot posts in the old #synapse-dev)

**Comment by bwindels** [comment]
Yeah, this would be part of #227 so will close as dupe. Thanks for reporting though!
