### ISSUE TITLE
Heroes aren't recalculate when someone leaves the room

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#591]
When in a DM with somebody that is migrating their account, they invite their other user into the DM, they join and the old user leaves.
In this case, the name for the DM in Hydrogen gets stuck at `User & User`, e.g. it doesn't seem to recalculate the name after the old user left.

After a refresh, everything is correct.

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by tech-bash** [comment]
I can try this one out !!
