### ISSUE TITLE
SDK example fails to start

### ISSUE THREAD

**Issue by juhanakristian** [vector-im/hydrogen-web#604]
**Describe the bug**
Starting the [SDK example](https://github.com/vector-im/hydrogen-web/blob/master/doc/SDK.md) fails with `No loader is configured for ".html"` when running `npm run dev`

```
error when starting dev server:
Error: Build failed with 1 error:
node_modules/hydrogen-web/src/sdk/paths/vite.ts:1:33: error: No loader is configured for ".html" files: node_modules/hydrogen-web/assets/download-sandbox.html?url
```

**To Reproduce**
1. Follow instructions in https://github.com/vector-im/hydrogen-web/blob/master/doc/SDK.md to setup a React project
2. Run `npm run dev`
3. Error will be printed to terminal

**Expected behavior**
The application starts in dev mode

**Additional context**
There are also errors related to indexeddb but they can be fixed by running `yarn add --dev fake-indexeddb`

**Comment by MadLittleMods** [comment]
For reference, when I tried the [latest SDK example](https://github.com/vector-im/hydrogen-web/blob/65dcf8bc360413a09be4d2b1ee48a051281b7109/doc/SDK.md), it worked out of the box 🎉
