### ISSUE TITLE
Pickup config.json changes at app startup rather than build

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#609]
Currently, the config.json file is only read at build time. To change for example the default home server, it would be nice if people deploying Hydrogen wouldn't have to run the build again.

One option would be to just disable caching for config.json like we do for index.html and read that before bootstrapping the app, but this would break offline and also cause a delay before the UI can be shown.

So we also need a caching strategy in the service worker that always returns what is in cache for config.json, if anything, and in the background updates it from the server if possible.

If caching is correctly disabled on the server, then applying config changes should just be a refresh away.

**Comment by llwp** [comment]
What do we think about reducing scope here as a potential first step... and detecting changes - but only applying certain types of (generally non breaking) changes? Just a thought.

Is there an issue for caching strategy in the service worker? That seems like a good approach and may be a prerequisite for a good full solution imho.
