### ISSUE TITLE
Create rooms

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#647]
Add create room functionality like element, with name & topic field, and public/private & e2ee switch.
Also add create DM option without any dialog in member info, just creates a private e2ee room.

**Comment by ibeckermayer** [comment]
@bwindels I'm testing out hydrogen, and I was able to create a new room, and it looked like all of "name & topic field, and public/private & e2ee switch". However I wasn't able to figure out how to invite people to the room, or how to create a DM. Are those not implemented yet?
