### ISSUE TITLE
Don't add public room searchable

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/hydrogen-web#648]
In every matrix client there have public room. And it makes unusable for family. In family everyone is not over 18 years old. There have below 18 years but most of the public home server they 18+ public room. it makes almost unusable for family to use matrix network.

You can add search by id example @hydrogen:matrix.org. Then it will be easier who want to join specific room. But if you make it searchable by name and show the public room the kids can easily join there.

**Comment by bwindels** [comment]
I'm trying to understand if there is an actual feature request here... As far as I can tell you want public rooms separated from direct messages (and private rooms?). This sounds mostly like #153, feel free to add a comment there if that doesn't fully cover your feature request.

Your second suggestion to hide public rooms by default and only show them if you filter the room list is not something we want in the app, sorry.

I'll close this is a duplicate for the issue above.

**Comment by AnisTaluqdar** [comment]
No, I didn't mean it. I mean element web have public room browsing options and you can search any public room by name. I said hydrogen web it can add the feature to search room by ID like @hydrogen:matrix.org . Not by name nor browsing the room.
