### ISSUE TITLE
Re-introduce CommonJS support to SDK

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/hydrogen-web#686]
It's not quite clear what the original problem is or how to reproduce but https://github.com/vector-im/hydrogen-web/pull/633/files removed CommonJS `exports` from the `package.json` to workaround a Vite bug.

With https://github.com/matrix-org/matrix-public-archive, I'm requiring `hydrogen-view-sdk` in Node.js. I'm currently [working around the CommonJS support](https://github.com/vector-im/hydrogen-web/pull/653) by just manually updating `package.json` with the `exports` again.

`package.json`
```json
{
  "main": "./hydrogen.cjs.js",
  "exports": {
      ".": {
          "import": "./lib-build/hydrogen.es.js",
          "require": "./lib-build/hydrogen.cjs.js"
      },
      "./paths/vite": "./paths/vite.js",
      "./style.css": "./style.css",
      "./assets/*": "./asset-build/assets/*"
  }
}
```

**Comment by bwindels** [comment]
Noted, I'm surprised though you can't use hydrogen-view-sdk as an ES module though from your commonjs project with node. Are you using an older version of node?

**Comment by MadLittleMods** [comment]
Node.js v16.14.0

If you try to `require('hydrogen-view-sdk')` as an ES module, Node.js throws:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\MLM\Documents\GitHub\element\hydrogen-web\target\hydrogen.es.js from C:\Users\MLM\Documents\GitHub\element\matrix-public-archive\server\render-hydrogen-to-string.js not supported.
Instead change the require of hydrogen.es.js in C:\Users\MLM\Documents\GitHub\element\matrix-public-archive\server\render-hydrogen-to-string.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by MadLittleMods** [comment]
While trying to solve this, I think I stumbled upon what the [`#vite-bug`](https://github.com/vector-im/hydrogen-web/blob/0ff1a01b429799e5ade9d21e0186ab0980b4add0/scripts/sdk/create-manifest.js#L6) was referring to -> https://github.com/vitejs/vite/discussions/6459. @bwindels looks like we both ran into the same issue 😁

**Comment by MadLittleMods** [comment]
It looks like this may have just been fixed by https://github.com/vitejs/vite/issues/6725 -> https://github.com/vitejs/vite/pull/7073 (literally 2 days ago) and we just need to wait for the next Vite release 🎉

Re-introduced the CommonJS exports in https://github.com/vector-im/hydrogen-web/pull/693 and will try it out the new Vite release

**Comment by MadLittleMods** [comment]
Commented on the status of this in the PR https://github.com/vector-im/hydrogen-web/pull/693#discussion_r815300546

> I played around with that fix and it still doesn't fix the situation for `*.html?url` or non-ESM `.js?url` imports, see https://github.com/vitejs/vite/pull/7097
