### ISSUE TITLE
Can't verify session

### ISSUE THREAD

**Issue by dzg** [vector-im/hydrogen-web#688]
When I login using Hydrogen, it never pops up verification request from other device ... so can't see encrypted chats. What am I missing? 

Over at https://github.com/vector-im/hydrogen-web/blob/master/doc/FAQ.md it says "click on the Hydrogen device and select Manually Verify by Text"

But I do not see that option in Element. Just "Verify"

![image](https://user-images.githubusercontent.com/466557/155601236-e9eedd6a-9d66-48a4-a52b-a84605b9d056.png)

**Comment by bwindels** [comment]
Verification isn't supported yet, and the verify button in the security settings above will indeed not work.You need to follow the exact instructions in the FAQ, meaning you go through the right panel to your own member details.
