### ISSUE TITLE
Cannot login: The operation is insecure..

### ISSUE THREAD

**Issue by mizzunet** [vector-im/hydrogen-web#696]
**Describe the bug**
I cannot login, I'm having this
Here's the logs: https://0x0.st/oKCo.json

**To Reproduce**
1. Go to the site 
2. Login

**Expected behavior**
Log in to my accounts

**Screenshots**
![image](https://user-images.githubusercontent.com/10193999/156033049-8eaf8507-a676-4154-ae2a-c2ea733676d4.png)

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Browser LibreWolf

**Comment by bwindels** [comment]
This is very likely https://github.com/vector-im/hydrogen-web/issues/313
