### ISSUE TITLE
hydrogen.element.io cannot find theme location

### ISSUE THREAD

**Issue by thigg** [vector-im/hydrogen-web#747]
**Describe the bug**
When using hydrogen.element.io from my android phone (SailfishOS) with FF78 it is only showing the text:

```
cannot find theme location for theme undefined
```

**To Reproduce**
1. Open hydrogen.element.io with FF78

**Expected behavior**
Login Page shows

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: Sailfishos
 - Browser : stock, FF78 based
 - Version 78.

**Comment by bwindels** [comment]
We deployed some fixes, is this still an issue on 0.2.32?

**Comment by thigg** [comment]
no, thanks for fixing it.
