### ISSUE TITLE
The /join command

### ISSUE THREAD

**Issue by Mikaela** [vector-im/hydrogen-web#792]
**Is your feature request related to a problem? Please describe.**

I cannot figure out how to join a room as it's not simple `/join #hydrogen:matrix.org` which is universal outside of Element iOS.

**Describe the solution you'd like**

I would like to have a `/join` command accepting the room alias and if the room is join rule `knock` or `knock_restricted` (and the user doesn't have access through allowed room) prompt for a knocking message and knock the room instead. I guess a separate /knock command would be nice or accepting join reason which could then be used as a knock reason?

**Describe alternatives you've considered**

None regarding /join, for /knock see above

**Additional context**

I found https://github.com/vector-im/hydrogen-web/pull/358 which implies joining is somehow supported, but I don't know how. I am using Hydrogen as a PWA, so I don't see the address bar.

Ref: #733 #775

**Comment by bbhtt** [comment]
https://github.com/vector-im/hydrogen-web/pull/809 will implement it I think.

> found https://github.com/vector-im/hydrogen-web/pull/358 which implies joining is somehow supported, but I don't know how. I am using Hydrogen as a PWA, so I don't see the address bar.

The only way I know is to replace the url with the room alias and reload, it'll show a join button. But I don't think it's possible to trigger that from the UI and with no address bar that won't be possible.
