### ISSUE TITLE
How to implement push notifications with hydrogen embedded

### ISSUE THREAD

**Issue by leccyril** [vector-im/hydrogen-web#818]
We trying to found how to implement push notifications to be able to have notifications even with our application closed

do you have a documentation to achieve this ?

thank you very much

**Comment by bwindels** [comment]
You need the service worker for this, which is currently not supported with the SDK.

**Comment by leccyril** [comment]
Hello ok thank you, so i try to understand, why it is managed on release or standalone server but not with SDK ? what is the difference exactly? why it is not implemented ? should it work if it works with standalone no ?

for example in our code we set automaticaLLY push enable ;

    	                                viewModel._updateSettings(true);
					const settingsViewModel = viewModel.settingsViewModel;
					settingsViewModel.pushNotifications.enabled = true;
					viewModel._updateSettings(false);

					await viewModel.start();
but we have this error 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'supportsPush')
    at SettingsViewModel.load (SettingsViewModel.js:80:84)

because notificationService is undefined, so my question why with SDK it is undefined and if we launch in webserver it will not be null ? i am really trying to understand the difference...
in platerform it is initialized in the platform init method, why it is not same case in SDK ?

thank you there is not really discussion about this topic so i think it can facilitate for every one, because on element i checked all messages and gus seems to be lost as me ...
