### ISSUE TITLE
Can't verify session

### ISSUE THREAD

**Issue by Justinzobel** [vector-im/hydrogen-web#826]
The README has a section called: How can I verify my session from Element?

You can only verify by comparing keys manually currently. In Element, go to your own profile in the right panel, click on the Hydrogen device and select Manually Verify by Text. The session key displayed should be the same as in the Hydrogen settings. You can't yet mark your Element session as trusted from Hydrogen.

However in Element I cannot see any option to Manually Verify by Text

**Comment by bwindels** [comment]
You need to go into the member panel for your own user in any room and click the Hydrogen device.

**Comment by Justinzobel** [comment]
Can you please add this into the README, it's not clear there.
