### ISSUE TITLE
Unable to log out of signed out session

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/hydrogen-web#865]
Unable to log out of signed out session

### Reproductions steps

 1. Have multiple sessions signed into Hydrogen
 1. From Element or another Matrix client, sign out the existing Hydrogen device session
 1. Open Hydrogen and choose the session you just signed out out of band.
 1. Notice the `Your token is no longer valid!` message and click proceed
    - ![](https://user-images.githubusercontent.com/558581/187588192-c4049be9-2764-40dc-abda-c430523078d8.png)
 1. Instead of signing in, just press the back button to go back to the list of sessions
    - <img src="https://user-images.githubusercontent.com/558581/187588268-937ddc4c-a763-4982-9ebe-e5fcdb7d6803.png" width="50%">
 1. Choose the same signed out session again
    - <img src="https://user-images.githubusercontent.com/558581/187588697-f0253713-45ab-47e1-bce3-5eb4d031c98e.png" width="50%">
 1. Notice the `Something went wrong` screen with an option with a `Log out` option
    - ![](https://user-images.githubusercontent.com/558581/187588344-e42be421-24eb-474c-b225-a2b8de182fd8.png)
 1. Clicking the `Log out` option has no effect and the following error is logged to the console
    ```
    Uncaught (in promise) TypeError: this._client.logout is not a function
        at SessionLoadViewModel.logout (SessionLoadViewModel.js:157:28)
        at HTMLButtonElement.onClick (SessionLoadStatusView.js:33:35)
    ```

### Environment

 - Latest Hydrogen `master`: 5f9cfffa3b547991b665f57a8bf715270a1b2ef1

**Comment by MidhunSureshR** [comment]
Can't reproduce on my end. On step 6, the signed out session does not show up in the list for me after a forced logout.

**Comment by MadLittleMods** [comment]
Things do seem to recover better now 👍

You still do get in to the paradox state if you visit non-existent session directly. For example, just visit https://hydrogen.element.io/#/session/doesnotexist/room/!vaRuaHMtoPkUtcRtCV%3Amatrix.org where pressing `Logout` just throws an `Error: Could not find session for id doesnotexist` error in the console and does nothing. `Go back` works as expected.

**Comment by moriel5** [comment]
I seem to be facing a similar session on my end, on other Matrix clients, where I have an old unused session that Matrix is unable to sign out of, however this is not a client issue, but a server issue (clients tested: nheko, Element-Android, Cinny-Desktop/Cinny-Web).
