### ISSUE TITLE
Notifications unavailable in GNOME Web (Epiphany)

### ISSUE THREAD

**Issue by darkdragon-001** [vector-im/hydrogen-web#884]
**Describe the bug**
Settings > Notifications tells me _"Push notifications are not supported on this browser"_ even though GNOME Web browser supports HTML5 Web Notifications. I tested that notifications work with Telegram Web on the same device/browser.

**To Reproduce**
1. Log into hydrogen.element.io
2. Click on Settings > Notifications
4. Read _"Push notifications are not supported on this browser"_

**Expected behavior**
Notifications should be available on GNOME Web.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pinephone
 - OS: Mobian
 - Browser: GNOME Web (Epiphany)
 - Version: 42.4

**Additional context**

**Comment by bwindels** [comment]
While GNOME Web may support showing notifications, it does not support web push. This would need #296, so closing this in favour of that.

**Comment by darkdragon-001** [comment]
Linking the Web Push support issue in GNOME Web / Epiphany here: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1871
