### ISSUE TITLE
e.startswith is not a function

### ISSUE THREAD

**Issue by ar1ja** [vector-im/hydrogen-web#941]
**Describe the bug**

**To Reproduce**
1. Go to <https://hydrogen.element.io/>
2. Login
3. Boom

**Expected behavior**
For it to not throw this error:

```
Something went wrong…
e.startsWith is not a function

This occurred while running Xt@https://hydrogen.element.io/assets/index.a5041cb5.js:19:6974.

_parseMxcUrl@https://hydrogen.element.io/assets/index.a5041cb5.js:1:14908
mxcUrlThumbnail@https://hydrogen.element.io/assets/index.a5041cb5.js:1:14475
Pe@https://hydrogen.element.io/assets/index.a5041cb5.js:13:151761
avatarUrl@https://hydrogen.element.io/assets/index.a5041cb5.js:16:1690
_avatarUrlChanged@https://hydrogen.element.io/assets/index.a5041cb5.js:20:8363
mount@https://hydrogen.element.io/assets/index.a5041cb5.js:20:8728
Xt@https://hydrogen.element.io/assets/index.a5041cb5.js:19:6937
view@https://hydrogen.element.io/assets/index.a5041cb5.js:20:6503
render@https://hydrogen.element.io/assets/index.a5041cb5.js:20:20441
mount@https://hydrogen.element.io/assets/index.a5041cb5.js:20:3961
Xt@https://hydrogen.element.io/assets/index.a5041cb5.js:19:6937
view@https://hydrogen.element.io/assets/index.a5041cb5.js:20:6503
mapView/<@https://hydrogen.element.io/assets/index.a5041cb5.js:20:6771
r@https://hydrogen.element.io/assets/index.a5041cb5.js:20:6184
update@https://hydrogen.element.io/assets/index.a5041cb5.js:20:4259
_updateFromValue@https://hydrogen.element.io/assets/index.a5041cb5.js:20:3051
emit/<@https://hydrogen.element.io/assets/index.a5041cb5.js:1:25057
emit@https://hydrogen.element.io/assets/index.a5041cb5.js:1:25045
emitChange@https://hydrogen.element.io/assets/index.a5041cb5.js:13:151122
_updateRoom/<@https://hydrogen.element.io/assets/index.a5041cb5.js:17:37739
emit@https://hydrogen.element.io/assets/index.a5041cb5.js:1:1730
set@https://hydrogen.element.io/assets/index.a5041cb5.js:1:2356
initialize@https://hydrogen.element.io/assets/index.a5041cb5.js:17:24712
```

**Screenshots**

![mpv-shot0002](https://user-images.githubusercontent.com/71613062/204092850-843cfd91-6bad-44c9-a315-c7d082476715.jpg)

**Comment by bwindels** [comment]
Can you submit the debug logs from the settings please? If you're unable to go to the settings from the UI, you can enter this in the console:
```js
location.href = __hydrogenViewModel.sessionViewModel.leftPanelViewModel.settingsUrl
__hydrogenViewModel.sessionViewModel.settingsViewModel.sendLogsToServer()
```

**Comment by ar1ja** [comment]
> Can you submit the debug logs from the settings please? If you're unable to go to the settings from the UI, you can enter this in the console:
> 
> ```js
> location.href = __hydrogenViewModel.sessionViewModel.leftPanelViewModel.settingsUrl
> __hydrogenViewModel.sessionViewModel.settingsViewModel.sendLogsToServer()
> ```

done

**Comment by ar1ja** [comment]
> Can you submit the debug logs from the settings please? If you're unable to go to the settings from the UI, you can enter this in the console:
> 
> ```js
> location.href = __hydrogenViewModel.sessionViewModel.leftPanelViewModel.settingsUrl
> __hydrogenViewModel.sessionViewModel.settingsViewModel.sendLogsToServer()
> ```

Any update on this ?

**Comment by sleroq** [comment]
This happens because `avatarUrl` can be an object. `{ content_uri: "mxc://server/media" }`

This maybe caused by rooms with GIF avatars

**Comment by ar1ja** [comment]
guess its solved
