### ISSUE TITLE
Cross signing: implement the shields

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#957]
Depends on #956 

implementing the shields (doing the signature verification but not signing yet), the signature is included in the section for the signed key in the /keys/query response for that user. We can't do this as the first point because we can't yet trust our own MSK, as we don't have a means of verifying either another client or verifying that the private key in 4S checks out with the published MSK.

we need the keys of all members in a room to be able to show the room shield. we probably at least want to show the shield in the room header when you open the room. Element does not show the shield in the left panel, probably precisely for this reason. Showing the shield implies tracking the room (downloading members, downloading their keys and tracking and member device changes) so does that render the optimizations to not track the room until we send our first message obsolete?

This will also include the signature verification caching framework that goes from the bottom up to the root of the trust tree as laid out in [a comment on the Epic](https://github.com/vector-im/hydrogen-web/issues/827#issuecomment-1277431499)

One crucial implementation note that Valere brought up is that a trusted flag should be a tri-state, not just a boolean: trusted, not trusted and dirty, e.g. need to do work to be able to determine,

 - implement signature validation of signature with parent key
 - implement signature validation of each level:
    - signature of other user device with their SSK
    - signature of other user MSK of their SSK
    - signature of other user MSK with our USK
    - signature of our device with our SSK
    - signature of our SSK with our MSK
 - aggregate trust for devices of user to trust of the user (e.g. any device not trusted, don't trust user)
 - aggregate trust for all users to trust for room (e.g. any user not trusted, don't trust room)
 - cache aggregation at user and room level

**Comment by bwindels** [comment]
Notes from the crypto team: https://hackmd.io/@ktO1wyrVSni2M6FoFrnW7Q/SyJWBMc_o

**Comment by bwindels** [comment]
First PR:
 - no caching yet
 - verify signature of MSK of user with our USK
 - verify signature of all of their device keys with their SSK
 - show shield in member panel

**Comment by bwindels** [comment]
Things that need to get a shield:
 - room events (verify that sender key is verified all the way up to our MSK)
 - room members (verify all their device keys are verified all the way up to our MSK)
 - rooms (check all members are verified)

**Comment by MidhunSureshR** [comment]
Closed in favor of #1052, #1053, #1054, #1055
