### ISSUE TITLE
Send DM

### ISSUE THREAD

**Issue by theslash** [vector-im/hydrogen-web#989]
Hi,
I feel very dumb, but I just tried the hydrogen instance on https://hydrogen.element.io/ 
and just don't get how I can send a direct message to another user on my Server?? I cant find the UI for searching for users etc.
Am I missing something here?
thanks for helping me

**Comment by bwindels** [comment]
It's a bit hidden indeed, you go into a room where the user you want to talk to is joined, open the room details, choose members, choose the member and pick "Direct Message" or something similar.

Fwiw, [#hydrogen-web:matrix.org](https://matrix.to/#/#hydrogen-web:matrix.org) is usually a better place to ask this than opening an issue.
